image:
  image: "ghcr.io/recmo/rust-service-template"
  tag: # Defaults to `v` + appVersion
  arch: amd64 # Either amd64 or arm64
  pullSecret:

labels:
  component: # Defaults to name
  partOf: rust-templates
  createdBy:

environment: prod
replicas: 1
region: "us-east-1"

canary:
  enabled: false

resources:
  requests:
    cpu: 0.1
    memory: 128Mi
  limits:
    cpu: 16.0
    memory: 4Gi

# Environment values can be strings or Kubernetes env objects
env:

# Spec ingress policy for the `api` and `metrics` port.
# Values are a list of NetworkPolicyPeer v1 objects, empty means allow all.
ingress:
  host: "rust-service-template.staging.xn--2-umb.com"
  api:
  metrics:
